[book]
authors = ["ruoran"]
language = "zh-cn"
src = "src"
title = "腐根之里设计文档"

[output.html]
mathjax-support = true

[preprocessor.add-references]
command = "cargo run --manifest-path=mdbook-add-references/Cargo.toml"
